[package]
name = "api"
version = "0.1.0"
edition = "2018"

[dependencies]
actix-web = "3"
actix-session = "0.4"
serde = "1.0"
serde_json = "1.0"
serde_derive = "1.0"
domain = { path = "../domain" }
database = { path = "../database" }